// <auto-generated />
namespace TutorialProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class FixingthisVersion : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FixingthisVersion));
        
        string IMigrationMetadata.Id
        {
            get { return "202506231731324_Fixing this Version"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
